name: QA Test and Deploy

concurrency: qa

on:
  push:
    branches:
      - 'qa**'

env:
  DB_NAME: wp_tests
  DB_USER: root
  DB_PASSWORD: root
  DB_HOST: 0.0.0.0
  COMPOSER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=3

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer, cs2pr

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Composer cache
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: NodeJS cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ hashFiles( 'package-lock.json' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: WP cache
        id: wp-cache
        uses: actions/cache@v4
        with:
          path: wp
          key: wp-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: WP plugins cache
        id: wp-plugins-cache
        uses: actions/cache@v4
        with:
          path: wp-content/plugins
          key: wp-plugins-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: Travelopia packages cache
        id: travelopia-packages-cache
        uses: actions/cache@v4
        with:
          path: wp-content/mu-plugins/travelopia
          key: travelopia-packages-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: WordPress Blade package cache
        id: wordpress-blade-cache
        uses: actions/cache@v4
        with:
          path: wp-content/mu-plugins/wordpress-blade
          key: wordpress-blade-package-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: Install Composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install

      - name: Install NodeJS dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: PHP Coding standards
        run: npm run lint:php

      - name: JS Coding standards
        run: npm run lint:js

      - name: CSS Coding standards
        run: npm run lint:css

      - name: PHPUnit Tests
        run: npm run test:php

      - name: PHP Static Analysis
        run: npm run static-analysis:php

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: qa

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, cs2pr

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Composer cache
        id: composer-deploy-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-deploy-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: NodeJS cache
        id: node-deploy-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-deploy-${{ hashFiles( 'package-lock.json' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: WP plugins cache
        id: wp-plugins-deploy-cache
        uses: actions/cache@v4
        with:
          path: wp-content/plugins
          key: wp-plugins-deploy-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: Travelopia packages cache
        id: travelopia-packages-deploy-cache
        uses: actions/cache@v4
        with:
          path: wp-content/mu-plugins/travelopia
          key: travelopia-packages-deploy-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: WordPress Blade package cache
        id: wordpress-blade-cache
        uses: actions/cache@v4
        with:
          path: wp-content/mu-plugins/wordpress-blade
          key: wordpress-blade-package-deploy-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/qa-tests-deploy.yml' ) }}

      - name: Install Composer dependencies
        if: steps.composer-deploy-cache.outputs.cache-hit != 'true'
        run: composer install --no-dev --optimize-autoloader

      - name: Install NodeJS dependencies
        if: steps.node-deploy-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build PHP, CSS and JS Assets
        run: npm run build

      - name: Deploy to Pantheon
        env:
          PANTHEON_SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}
          PANTHEON_GIT_REPOSITORY: ${{ secrets.PANTHEON_MS_GIT_REPOSITORY }}
          PANTHEON_GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
        run: bash .bin/deploy.sh
